import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import {
  formatCurrency,
  formatDate,
  getCustomerStats,
  normalizePhoneForWhatsApp,
} from './storage'

export function downloadCustomerPDF(customer, business = {}) {
  const doc = new jsPDF()
  const stats = getCustomerStats(customer)
  const shopName = business.name || 'Digital Khata'
  const shopPhone = business.phone || ''
  const shopAddress = business.address || ''

  doc.setFillColor(24, 95, 165)
  doc.rect(0, 0, 210, 32, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(shopName, 14, 14)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  let sub = 'Account Statement'
  if (shopPhone) sub += '  |  ' + shopPhone
  doc.text(sub, 14, 22)
  if (shopAddress) {
    doc.setFontSize(8)
    doc.text(shopAddress, 14, 28)
  }

  doc.setTextColor(30, 30, 30)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Customer', 14, 42)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(customer.name || '—', 14, 49)

  let yInfo = 49
  if (customer.phone) {
    yInfo += 6
    doc.setFontSize(9)
    doc.setTextColor(80, 80, 80)
    doc.text('Phone: ' + customer.phone, 14, yInfo)
  }
  if (customer.address) {
    yInfo += 5
    doc.setFontSize(9)
    doc.text('Address: ' + customer.address, 14, yInfo)
  }

  const y0 = yInfo + 10
  doc.setDrawColor(220, 220, 220)
  doc.setFillColor(240, 247, 255)
  doc.roundedRect(14, y0, 58, 18, 2, 2, 'FD')
  doc.setFillColor(240, 253, 244)
  doc.roundedRect(76, y0, 58, 18, 2, 2, 'FD')
  doc.setFillColor(254, 242, 242)
  doc.roundedRect(138, y0, 58, 18, 2, 2, 'FD')

  doc.setFontSize(8)
  doc.setTextColor(24, 95, 165)
  doc.text('TOTAL DEBIT', 18, y0 + 6)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(formatCurrency(stats.totalAmount), 18, y0 + 13)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(59, 109, 17)
  doc.text('RECEIVED', 80, y0 + 6)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(formatCurrency(stats.totalReceived), 80, y0 + 13)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(226, 75, 74)
  doc.text('PENDING', 142, y0 + 6)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(formatCurrency(stats.pending), 142, y0 + 13)

  const txs = [...(customer.transactions || [])].sort((a, b) =>
    (a.date || '').localeCompare(b.date || '')
  )
  const rows = txs.map((tx) => {
    const bal = (Number(tx.amount) || 0) - (Number(tx.received) || 0)
    return [
      formatDate(tx.date),
      tx.billNo || '—',
      tx.amount ? formatCurrency(tx.amount) : '—',
      tx.received ? formatCurrency(tx.received) : '—',
      formatDate(tx.receivedDate),
      formatCurrency(bal),
    ]
  })

  autoTable(doc, {
    startY: y0 + 24,
    head: [['Date', 'Bill No', 'Amount', 'Received', 'Rec. Date', 'Balance']],
    body: rows.length ? rows : [['—', '—', '—', '—', '—', '—']],
    theme: 'striped',
    headStyles: {
      fillColor: [24, 95, 165],
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold',
    },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      2: { halign: 'right' },
      3: { halign: 'right' },
      5: { halign: 'right' },
    },
    margin: { left: 14, right: 14 },
  })

  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      'Generated by Digital Khata  |  ' +
        new Date().toLocaleString('en-GB') +
        '  |  Page ' +
        i +
        '/' +
        pageCount,
      14,
      290
    )
  }

  const safeName = (customer.name || 'customer').replace(/[^\w\-]+/g, '_')
  doc.save(safeName + '_statement.pdf')
  return doc
}

/** Build WhatsApp text — pending vs settled */
export function buildWhatsAppMessage(customer, business = {}) {
  const stats = getCustomerStats(customer)
  const shop = business.name || 'Digital Khata'
  const pending = stats.pending

  if (pending <= 0) {
    return [
      `*${shop}*`,
      '',
      `Assalam-o-Alaikum ${customer.name || 'Customer'},`,
      '',
      'Aap ka Debit *clear* ho chuka hai. ✅',
      `Total Debit: ${formatCurrency(stats.totalAmount)}`,
      `Total Received: ${formatCurrency(stats.totalReceived)}`,
      `Pending: ${formatCurrency(0)}`,
      '',
      'Aap ke ehtimam aur barwaqt payment ka *dil se shukriya*.',
      'Humari services dobara istemal karne ka intezar rahega.',
      '',
      'JazakAllah Khair',
      `*${shop}*`,
    ].join('\n')
  }

  return [
    `*${shop} — Hisab / Statement*`,
    '',
    `Assalam-o-Alaikum ${customer.name || 'Customer'},`,
    '',
    'Aap ke account ka Balance yeh hai:',
    '',
    `• Total Debit: *${formatCurrency(stats.totalAmount)}*`,
    `• Received: *${formatCurrency(stats.totalReceived)}*`,
    `• *Pending Balance: ${formatCurrency(pending)}*`,
    '',
    'Barwaqt pending clear karne ki request hai.',
    'Koi masla ho to rabta karein.',
    '',
    'Shukriya',
    `*${shop}*`,
  ].join('\n')
}

export function openWhatsAppText(customer, business = {}) {
  const phone = normalizePhoneForWhatsApp(customer.phone)
  if (!phone) {
    alert('Customer phone number missing or invalid. Please add a valid phone first.')
    return false
  }
  const text = encodeURIComponent(buildWhatsAppMessage(customer, business))
  window.open('https://wa.me/' + phone + '?text=' + text, '_blank')
  return true
}

/** PDF download + WhatsApp text (attach PDF manually / share on mobile) */
export async function openWhatsAppWithPDF(customer, business = {}) {
  const phone = normalizePhoneForWhatsApp(customer.phone)
  if (!phone) {
    alert('Customer phone number missing or invalid. Please add a valid phone first.')
    return false
  }

  const stats = getCustomerStats(customer)
  const shop = business.name || 'Digital Khata'
  const safeName = (customer.name || 'customer').replace(/[^\w\-]+/g, '_')

  // Generate PDF blob
  const doc = new jsPDF()
  // reuse download logic by calling download then also open WA
  downloadCustomerPDF(customer, business)

  const note =
    stats.pending <= 0
      ? `*${shop}*\n\nAssalam-o-Alaikum ${customer.name},\n\nAap ka account clear hai. Statement PDF attach hai.\nShukriya!`
      : `*${shop} — Statement*\n\nAssalam-o-Alaikum ${customer.name},\n\nPending: *${formatCurrency(stats.pending)}*\n\nStatement PDF download ho gayi hai — please usay attach karke bhej dein / mobile pe share karein.`

  window.open('https://wa.me/' + phone + '?text=' + encodeURIComponent(note), '_blank')
  return true
}
